CornNuggets/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CornNuggets.DataAccess;
using CornNuggets.DataAccess.Models;
using CornNuggets.DataAccess.Repositories;

namespace CornNuggets.WebUI.Controllers
{
    public class CustomersController : Controller
    {
        private readonly CornNuggetsContext _context;
        readonly CornNuggetsRepository repository = new CornNuggetsRepository(); 
        public CustomersController(CornNuggetsContext context)
        {
            _context = context;
            repository = new CornNuggetsRepository(_context);
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            
            return View(await _context.Customers.ToListAsync());
        }
        public IActionResult Search(string fname, string lname)
        {
            var listing = from Customers in _context.Customers
                          where Customers.FirstName == fname
                          where Customers.LastName == lname
                          select Customers;
            return View(listing);
        }
        // GET: Customers/Details/5

        public async Task<IActionResult> Details(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            var customers = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customers == null)
            {
                return NotFound();
            }
            
            return View(customers);
        }

        // GET: Customers/Create
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]        
        public async Task<IActionResult> Create([Bind("FirstName,LastName,PreferredStore")] Customers customer)
        {
            if (ModelState.IsValid)
            {
                
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return Redirect("/");
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customers = await _context.Customers.FindAsync(id);
            if (customers == null)
            {
                return NotFound();
            }
            ViewData["StoreName"] = new SelectList(_context.NuggetStores, "PreferredStore", "StoreName", customers.PreferredStore);
            return View(customers);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,FirstName,LastName,PreferredStore")] Customers customers)
        {
            if (id != customers.CustomerId)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomersExists(customers.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreName"] = new SelectList(_context.NuggetStores, "PreferredStore", "StoreName", customers.PreferredStore);
            return View(customers);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customers = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customers == null)
            {
                return NotFound();
            }

            return View(customers);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customers = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomersExists(int id)
        {
            return _context.Customers.Any(e => e.CustomerId == id);
        }
    }
}

CornNuggets/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CornNuggets.DataAccess;
using CornNuggets.DataAccess.Models;
using CornNuggets.DataAccess.Repositories;

namespace CornNuggets.WebUI.Controllers
{
    public class OrdersController : Controller
    {
        private readonly CornNuggetsContext _context;

        public OrdersController(CornNuggetsContext context)
        {
            _context = context;
            var repo = new CornNuggetsRepository();

        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var cornNuggetsContext = _context.Orders.Include(o => o.Customer).Include(o => o.Store).Include(o=> o.OrderLog);
            return View(await cornNuggetsContext.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Form(int? orderId)
        {
            if (orderId==null)
            {
                return NotFound();
            }
            var orders = await _context.Orders
                .Include(s => s.StoreId)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.CustomerId == orderId);

            if (orders ==null)
            {
                return NotFound();
            }    
            //var byId = new FormViewModel();
            //var result = byId.Repo.GetOrdersDetails(orderId);
            return View(orders);
        }
        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.Store)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }
        [HttpPost]
        public IActionResult Search(int custId)
        {
            var listing = from Orders in _context.Orders
                          where Orders.CustomerId == custId
                          select Orders;
            return View(listing);
        }

        public IActionResult Stores(int store)
        {
            var listing = from Orders in _context.Orders
                          where Orders.StoreId == store
                          select Orders;

            ViewData["orderId"] = new SelectList(_context.Orders, "orderId", "Order ID:");
            return View(listing);
        }


        // GET: Orders/Create
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Orders, "CustomerId", "Customer ID:");
            ViewData["StoreId"] = new SelectList(_context.NuggetStores, "StoreId", "StoreId");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,DateTimeStamp,StoreId,CustomerId,Total")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Orders, "CustomerId", "CustomerId", orders.CustomerId);
            ViewData["StoreId"] = new SelectList(_context.Orders, "StoreId", "StoreId", orders.StoreId);
            return View(orders);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "PreferredStore", orders.CustomerId);
            ViewData["StoreId"] = new SelectList(_context.NuggetStores, "StoreId", "StoreName", orders.StoreId);
            return View(orders);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,DateTimeStamp,StoreId,CustomerId,Total")] Orders orders)
        {
            if (id != orders.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdersExists(orders.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "PreferredStore", orders.CustomerId);
            ViewData["StoreId"] = new SelectList(_context.NuggetStores, "StoreId", "StoreName", orders.StoreId);
            return View(orders);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.Store)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orders = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(orders);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdersExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

CornNuggets/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CornNuggets.DataAccess;
using CornNuggets.DataAccess.Models;

namespace CornNuggets.WebUI.Controllers
{
    public class ProductsController : Controller
    {
        private readonly CornNuggetsContext _context;

        public ProductsController(CornNuggetsContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }
        [HttpGet]
        public async Task<IActionResult> Form()
        {
            return View(await _context.Products.ToListAsync());
        }
        [HttpPost]
        public IActionResult Form([Bind("ProductId,ProductName,ProductPrice,Inventory")] Products products)
        {
            return Redirect("/");
        }
        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["ProductName"] = new SelectList(_context.Products, "ProductName", "Product Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductPrice,Inventory")] Products products)
        {
            if (ModelState.IsValid)
            {
                _context.Add(products);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products.FindAsync(id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ProductPrice,Inventory")] Products products)
        {
            if (id != products.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(products);
                    
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(products.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var products = await _context.Products.FindAsync(id);
            _context.Products.Remove(products);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

CornNuggets/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us";
}
<h1 class="card-title">@ViewData["Title"]</h1>

<p class="content">
    Corn Nuggets is a catering business with wholesome and tasty treats that can be added to any party. We currently have over 15 stores, across the United States, 
    to choose from. You can order for pick up or delivery. Please provide 24 business hours notice for a catering delivery and set up.  We look forward to working with you.</p>

CornNuggets/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1  class="card-title" >Corn Nuggets Store Operations </h1>
        <table style="width:100%">

            <tr>
                <td>
                    <img src="https://live.staticflickr.com/65535/49755529223_c76d51898a_m.jpg" /><br />
                    <a type="button" asp-area="" asp-controller="Customers" asp-action="Index">Customer Lookup</a>
                </td>
                <td>
                    <img src="https://live.staticflickr.com/65535/49756394112_f349d09a53_m.jpg" /><br />
                    <a type="button" asp-area="" asp-controller="Orders" asp-action="Create">Place New Order</a>
                </td>
                <td>
                    <img src="https://live.staticflickr.com/65535/49756057036_94c45c8270_m.jpg" /><br />
                    <a type="button" asp-area="" asp-controller="Customers" asp-action="Create">New Customer</a>
                </td>
            </tr>
            <tr>
                <td>
                    <p class="content">Search for a customer by name.</p>
                </td>
                <td>
                    <p class="content">Place an order for a customer at their preferred store.</p>
                </td>
                <td>
                    <p class="content">Add a new customer.</p>
                </td>
            </tr>
            <tr>
                <td>
                    .
                </td>
                <td>
                    .
                </td>                    
                <td>
                    .
                </td>
            </tr>            
            <tr>
                <td>
                    .
                </td>
                <td>
                    .
                <td>
                    .
                </td>
            </tr>
            <tr>
                <td>
                    <img src="https://live.staticflickr.com/65535/49756394132_58a9d56297_m.jpg" /><br />
                    <a type="button" asp-area="" asp-controller="Orders" asp-action="Index">Customer Order History</a>
                </td>
                <td>
                    <img src="https://live.staticflickr.com/65535/49755529238_18a339c648_m.jpg" /><br />
                    <a type="button" asp-area="" asp-controller="Orders" asp-action="Index">Store Order History</a>
                <td>
                    <img src="https://live.staticflickr.com/65535/49756057091_2ac994d896_m.jpg" /><br />
                    <a type="button" asp-area="" asp-controller="OrderLogs" asp-action="Index">View Order Details</a>
                </td>
            </tr>
            <tr>
                <td>
                    <p class="content">Display all order history of a customer.</p>
                </td>
                <td>
                    <p class="content">Display all order history of a store.</p>
                </td>
                <td>
                    <p class="content">Display details of an order.</p>
                </td>
            </tr>

            <tr>
                <td>
                    .
                </td>
                <td>
                    .
                </td>
                <td>
                    .
                </td>
            </tr>
            <tr>
                <td>
                    .
                </td>
                <td>
                    .
                </td>
                <td>
                    .
                </td>
            </tr>
            <tr>
                <td>
                    
                </td>
                <td>
                    <img src="https://live.staticflickr.com/65535/49755529178_a556ae9f31_m.jpg" /><br />
                    <a type="button" asp-area="" asp-controller="Products" asp-action="Index">Product Pricing</a>
                </td>
                <td>
                    
                </td>
            </tr>
        </table>
        <br />
        <br>
        <p></p>
    </div>
    