CornNuggets/Models/Orders.cs
using System;
using System.Collections.Generic;

namespace CornNuggets.WebUI.Models
{
    public partial class Orders
    {
        public Orders()
        {
            OrderLog = new HashSet<OrderLog>();
        }

        public int OrderId { get; set; }
        public DateTime? DateTimeStamp { get; set; }
        public int? StoreId { get; set; }
        public int? CustomerId { get; set; }
        public decimal Total { get; set; }

        public virtual Customers Customer { get; set; }
        public virtual NuggetStores Store { get; set; }
        public virtual ICollection<OrderLog> OrderLog { get; set; }
    }
}

CornNuggets/Controllers/OrderLogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CornNuggets.DataAccess;
using CornNuggets.DataAccess.Models;

namespace CornNuggets.WebUI.Controllers
{
    public class OrderLogsController : Controller
    {
        private readonly CornNuggetsContext _context;

        public OrderLogsController(CornNuggetsContext context)
        {
            _context = context;
        }

        // GET: OrderLogs
        public async Task<IActionResult> Index()
        {
            var cornNuggetsContext = _context.OrderLog.Include(o => o.Order).Include(o => o.Product);
            
            return View(await cornNuggetsContext.ToListAsync());
        }

        // GET: OrderLogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderLog = await _context.OrderLog
                .Include(o => o.Order)
                .Include(o => o.Product)
                .FirstOrDefaultAsync(m => m.LogId == id);

            if (orderLog == null)
            {
                return NotFound();
            }
            orderLog.SubTotal = (int)(orderLog.ProductId *orderLog.ProductQty);
            return View(orderLog);
        }

        // GET: OrderLogs/Create
        public IActionResult Create()
        {
            ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "OrderId");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId");
            return View();
        }

        // POST: OrderLogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LogId,OrderId,ProductId,ProductQty,SubTotal")] OrderLog orderLog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderLog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "OrderId", orderLog.OrderId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", orderLog.ProductId);
            return View(orderLog);
        }
        [HttpPost]
        public IActionResult Search(int orderId)
        {
            var listing = from OrderLog in _context.OrderLog
                          where OrderLog.OrderId == orderId
                          select OrderLog;
            
            return View(listing);
        }
        // GET: OrderLogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderLog = await _context.OrderLog.FindAsync(id);
            if (orderLog == null)
            {
                return NotFound();
            }

            ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "OrderId", orderLog.OrderId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", orderLog.ProductId);
            
            return View(orderLog);
        }

        // POST: OrderLogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LogId,OrderId,ProductId,ProductQty,SubTotal")] OrderLog orderLog)
        {
            if (id != orderLog.LogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderLog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderLogExists(orderLog.LogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "OrderId", orderLog.OrderId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", orderLog.ProductId);
            return View(orderLog);
        }

        // GET: OrderLogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderLog = await _context.OrderLog
                .Include(o => o.Order)
                .Include(o => o.Product)
                .FirstOrDefaultAsync(m => m.LogId == id);
            if (orderLog == null)
            {
                return NotFound();
            }

            return View(orderLog);
        }

        // POST: OrderLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderLog = await _context.OrderLog.FindAsync(id);
            _context.OrderLog.Remove(orderLog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderLogExists(int id)
        {
            return _context.OrderLog.Any(e => e.LogId == id);
        }
    }
}

CornNuggets/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CornNuggets.DataAccess;
using CornNuggets.DataAccess.Models;
using CornNuggets.DataAccess.Repositories;

namespace CornNuggets.WebUI.Controllers
{
    public class OrdersController : Controller
    {
        private readonly CornNuggetsContext _context;

        public OrdersController(CornNuggetsContext context)
        {
            _context = context;
            var repo = new CornNuggetsRepository();

        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var cornNuggetsContext = _context.Orders.Include(o => o.Customer).Include(o => o.Store).Include(o=> o.OrderLog);
            return View(await cornNuggetsContext.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Form(int? orderId)
        {
            if (orderId==null)
            {
                return NotFound();
            }
            var orders = await _context.Orders
                .Include(s => s.StoreId)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.CustomerId == orderId);

            if (orders ==null)
            {
                return NotFound();
            }    
            //var byId = new FormViewModel();
            //var result = byId.Repo.GetOrdersDetails(orderId);
            return View(orders);
        }
        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.Store)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }
        [HttpPost]
        public IActionResult Search(int custId)
        {
            var listing = from Orders in _context.Orders
                          where Orders.CustomerId == custId
                          select Orders;
            return View(listing);
        }

        public IActionResult Stores(int store)
        {
            var listing = from Orders in _context.Orders
                          where Orders.StoreId == store
                          select Orders;

            ViewData["orderId"] = new SelectList(_context.Orders, "orderId", "Order ID:");
            return View(listing);
        }


        // GET: Orders/Create
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Orders, "CustomerId", "Customer ID:");
            ViewData["StoreId"] = new SelectList(_context.NuggetStores, "StoreId", "StoreId");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,DateTimeStamp,StoreId,CustomerId,Total")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Orders, "CustomerId", "CustomerId", orders.CustomerId);
            ViewData["StoreId"] = new SelectList(_context.Orders, "StoreId", "StoreId", orders.StoreId);
            return View(orders);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "PreferredStore", orders.CustomerId);
            ViewData["StoreId"] = new SelectList(_context.NuggetStores, "StoreId", "StoreName", orders.StoreId);
            return View(orders);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,DateTimeStamp,StoreId,CustomerId,Total")] Orders orders)
        {
            if (id != orders.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdersExists(orders.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "PreferredStore", orders.CustomerId);
            ViewData["StoreId"] = new SelectList(_context.NuggetStores, "StoreId", "StoreName", orders.StoreId);
            return View(orders);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.Store)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orders = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(orders);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdersExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

CornNuggets/Views/Orders/AddToOrder.cshtml
@model CornNuggets.DataAccess.Models.OrderLog

@{
    ViewData["Title"] = "AddToOrder";
}

    <h1 class="card-title">AddToOrder</h1>

<h4>OrderLog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddToOrder">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LogId" />
            <div class="form-group">
                <label asp-for="OrderId" class="control-label"></label>
                <select asp-for="OrderId" class="form-control" asp-items="ViewBag.OrderId"></select>
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductQty" class="control-label"></label>
                <input asp-for="ProductQty" class="form-control" />
                <span asp-validation-for="ProductQty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubTotal" class="control-label"></label>
                <input asp-for="SubTotal" class="form-control" />
                <span asp-validation-for="SubTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CornNuggets/Views/Orders/Create.cshtml
@model CornNuggets.DataAccess.Models.Orders

@{
    ViewData["Title"] = "Create";
}

    <h1 class="card-title">Create</h1>

<h4>Orders</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <select asp-for="StoreId" class="form-control" asp-items="@ViewBag.StoreId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" asp-items="@ViewBag.CustomerId" min="100000000" />
            </div>               
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" asp-area="" asp-controller="OrderLogs" asp-action="Create"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back To List</a>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CornNuggets/Views/Orders/Delete.cshtml
@model CornNuggets.DataAccess.Models.Orders

@{
    ViewData["Title"] = "Delete";
}

    <h1 class="card-title">Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Orders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTimeStamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.PreferredStore)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.StoreName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CornNuggets/Views/Orders/Details.cshtml
@model CornNuggets.DataAccess.Models.Orders

@{
    ViewData["Title"] = "Details";
}

    <h1 class="card-title">Details</h1>

<div>
    <h4>Orders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTimeStamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.PreferredStore)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.StoreName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.OrderId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CornNuggets/Views/Orders/Edit.cshtml
@model CornNuggets.DataAccess.Models.Orders

@{
    ViewData["Title"] = "Edit";
}

    <h1 class="card-title">Edit</h1>

<h4>Orders</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="OrderId" class="control-label"></label>
                @Model.OrderId

            </div>
            <div class="form-group">
                <label asp-for="DateTimeStamp" class="control-label"></label>
                @Model.DateTimeStamp
                
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <select asp-for="StoreId" class="form-control" asp-items="ViewBag.StoreId"></select>
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                @Model.CustomerId
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                @Model.Total
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CornNuggets/Views/Orders/Form.cshtml
@model CornNuggets.DataAccess.Models.Orders

@{
    ViewData["Title"] = "Form";
}

    <h1 class="card-title">Form</h1>

<div>
    <h4>Orders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTimeStamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.StoreName)
        </dd>
    </dl>
</div>
<div>
    <a type="button" asp-area="" asp-controller="OrderLogs" asp-action="Index">Add To Order</a>
    <a asp-action="Edit" asp-route-id="@Model.OrderId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CornNuggets/Views/Orders/Index.cshtml
@model IEnumerable<CornNuggets.DataAccess.Models.Orders>

@{
    ViewData["Title"] = "Index";
}

    <h1 class="card-title">Orders History</h1>


<a asp-action="Create">Create New</a>
<form asp-action="Search" method="post">
    <input type="text" name="custId" placeholder="By Customer Number" required/>
    <input type="submit" value="Filter" required />
</form><br />
<form asp-action="Stores" method="post">

    <input type="text" name="store" placeholder="By Store Number" />
    <input type="submit" value="Filter" />
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateTimeStamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderId)
            </th>   
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Store)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateTimeStamp)
            </td>
            <td>
                @item.OrderId
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Store.StoreName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CornNuggets/Views/Orders/Search.cshtml
@model IEnumerable<CornNuggets.DataAccess.Models.Orders>

@{
    ViewData["Title"] = "Search";
}

    <h1 class="card-title">Search</h1>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateTimeStamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(Model=> Model.Customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Store)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateTimeStamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StoreId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CornNuggets/Views/Orders/Stores.cshtml
@model IEnumerable<CornNuggets.DataAccess.Models.Orders>

@{
    ViewData["Title"] = "Stores";
}

    <h1 class="card-title">Stores</h1>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateTimeStamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Store)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateTimeStamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StoreId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>